#include "nomadz_motion_control/mof_compiler.hpp"

#include <fstream>
#include <cstdarg>
#include <cstring>
#include <dirent.h>
#include <string>
#include <iostream>
#include <map>
#include <filesystem>

#include <ament_index_cpp/get_package_share_directory.hpp>

#include "nomadz_motion_control/joint_stiffnesses.hpp"
#include "nomadz_motion_control_msgs/special_action_request_enums.hpp"

using nomadz_definitions::legacy_joint_indexes::NUM_JOINTS;
using nomadz_motion_control_msgs::SpecialActionType;

namespace nomadz_motion_control {

  int MofCompiler::myprintf(const char* format, ...) {
    va_list args;
    va_start(args, format);
    size_t size = strlen(print_buffer_);
    return vsnprintf(print_buffer_ + size, print_buffer_size_ - size, format, args);
  }

  MofCompiler::MofCompiler() {

    installation_root_directory_ = ament_index_cpp::get_package_share_directory("nomadz_motion_control");

    mof_file_map_.insert(position(SpecialActionType::PLAY_DEAD, "playDead"));
    mof_file_map_.insert(position(SpecialActionType::GO_UP, "goUp"));
    mof_file_map_.insert(position(SpecialActionType::SIT_DOWN, "sitDown"));
    mof_file_map_.insert(position(SpecialActionType::STAND, "stand"));
    mof_file_map_.insert(position(SpecialActionType::STAND_HIGH, "standHigh"));
    mof_file_map_.insert(position(SpecialActionType::FALL_PROTECTION_BACK, "fallProtectionBack"));
    mof_file_map_.insert(position(SpecialActionType::FALL_PROTECTION_FRONT, "fallProtectionFront"));
    mof_file_map_.insert(position(SpecialActionType::FALL_PROTECTION_SIDE, "fallProtectionSide"));
    mof_file_map_.insert(position(SpecialActionType::GET_UP_BACK_NAO_22, "getUpBackNao22"));
    mof_file_map_.insert(position(SpecialActionType::GET_UP_FRONT_NAO_22, "getUpFrontNao22"));
    mof_file_map_.insert(position(SpecialActionType::SIT_DOWN_GOALKEEPER, "sitDownKeeper"));
  }

  MofCompiler::~MofCompiler() {
    for (int i = 0; i < num_of_lines_; ++i) {
      delete line_data_[i];
    }

    for (int i = 0; i < num_of_files_; ++i) {
      delete file_name_[i];
    }

    for (int i = 0; i < num_of_labels_; ++i) {
      delete label_name_[i];
      delete label_motion_[i];
    }
  }

  // NOLINTBEGIN(readability-function-cognitive-complexity)
  bool MofCompiler::generateMotionNet() {
    char s[256];
    sprintf(s, "%s/config", installation_root_directory_.c_str());
    std::filesystem::create_directories(s);
    sprintf(s, "%s/special_actions.dat", s);

    std::ofstream stream;
    stream.open(s, std::ios::out);
    stream << "//\n";
    stream << "// This file contains the special actions and was\n";
    stream << "// generated by the Universal Resource Compiler\n";
    stream << "//\n";

    stream << "\n// jump table:\n";
    for (int i : jump_table_) {
      stream << i << " ";
    }

    stream << "\n\n// number of nodes:\n" << num_of_lines_ << "\n\n";

    stream << "// nodes:\n";
    int labelnum = 0;
    int filenum = 0;
    for (int i = 0; i < num_of_lines_; ++i) {
      if (file_start_index_[filenum] == i) {
        ++filenum;
      }
      if (label_number_[labelnum] == i) {
        ++labelnum;
      }
      if (strncmp(line_data_[i], "transition", 10) == 0) {
        char request[512];
        char viamotion[512];
        char vialabel[512];
        sscanf(line_data_[i] + 11, "%s %s %s", request, viamotion, vialabel);
        // check if label exists (request was already checked)

        bool found = false;
        int j;
        for (j = 0; j < num_of_labels_; ++j) {
          if (strcmp(label_motion_[j], viamotion) == 0 && strcmp(label_name_[j], vialabel) == 0) {
            found = true;
            break;
          }
        }
        if (!found) {
          for (int k = num_of_files_ - 1; k >= 0; --k) {
            if (file_start_index_[k] <= i) {
              myprintf("%s(%i) : error: jump label unknown\n", file_name_[k], line_number_[i]);
              return false;
            }
          }
        }

        if (strcmp(request, "allMotions") != 0) {
          stream << "1 " << label_number_[j] << " " << static_cast<int>(mof_file_map_.right.at(request));
        } else {
          stream << "2 " << label_number_[j];
        }
      } else if (strncmp(line_data_[i], "hardness", 8) == 0) {
        stream << "4 " << (line_data_[i] + 9);
      } else {
        stream << "3 " << line_data_[i];
      }

      if (line_motion_id_[i] >= 0) {
        stream << " " << line_motion_id_[i];
      } else {
        stream << " -1";
      }

      if (i < num_of_lines_ - 1) {
        stream << "\n";
      }
    }

    stream.close();
    return true;
  }

  bool MofCompiler::parseMotionFiles() {
    num_of_files_ = 0;
    dirent* ff = nullptr;

    char ffname[1024];
    sprintf(ffname, "%s/config/mofs", installation_root_directory_.c_str());

    bool there_are_more;
    DIR* fd = opendir(ffname);
    if (fd != nullptr) {
      do {
        ff = readdir(fd);
        there_are_more = ff != nullptr;
      } while (there_are_more && (strcmp(ff->d_name, ".mof") <= 0 || strlen(ff->d_name) <= 4));
    } else {
      there_are_more = false;
    }

    while (there_are_more) {
      if (strcmp(ff->d_name, "extern.mof") != 0) {
        char name[512];
        sprintf(name, "%s/config/mofs/%s", installation_root_directory_.c_str(), ff->d_name);
        FILE* f = fopen(name, "r");
        if (f == nullptr) {
          myprintf("error opening %s. Aborting.\n", name);
          return false;
        }
        file_name_[num_of_files_] = strdup(name);
        file_start_index_[num_of_files_++] = static_cast<short>(num_of_lines_);
        bool this_mof_has_labels = false;
        strcpy(motion_, ff->d_name);
        if (strcmp(motion_ + strlen(motion_) - 4, ".mof") == 0) {
          motion_[strlen(motion_) - 4] = 0;
        }
        act_motion_id_ = -1;
        for (int j = 0; j < NUM_SPECIAL_ACTIONS; ++j) {
          if (strcmp(mof_file_map_.left.at(static_cast<SpecialActionType>(j)).c_str(), motion_) == 0) {
            act_motion_id_ = j;
            break;
          }
        }

        char s[128000];
        size_t siz = fread(s, 1, 128000, f);
        fclose(f);
        if (siz > 0) {
          s[siz] = 0;
          char* t = &s[0];
          int line = 1;
          while (*t != 0) {
            char* u = strchr(t, '\n');
            if (u >= t) {
              *u = 0;

              char sval[NUM_JOINTS + 3][256]; // joints + interpolate + duration + bad argument
              int c = sscanf(
                t,
                "%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s", //(numOfJoints
                                                                                                          // + 3) * % s
                sval[0],
                sval[1],
                sval[2],
                sval[3],
                sval[4],
                sval[5],
                sval[6],
                sval[7],
                sval[8],
                sval[9],
                sval[10],
                sval[11],
                sval[12],
                sval[13],
                sval[14],
                sval[15],
                sval[16],
                sval[17],
                sval[18],
                sval[19],
                sval[20],
                sval[21],
                sval[22],
                sval[23],
                sval[24],
                sval[25],
                sval[26],
                sval[27],
                sval[28]); // sval[0]..sval[numOfJoints + 2]
              if (c == -1 || sval[0][0] == '"' || strncmp(sval[0], "//", 2) == 0) {
                // skip comments and empty lines by doing nothing
              } else if (strcmp(sval[0], "motion_id") == 0) {
                // if there is a motion_id we use it, otherwise filename
                if (strcmp(sval[1], "=") == 0 && c == 3) {
                  strcpy(motion_, sval[2]);
                  for (int j = 0; j < NUM_SPECIAL_ACTIONS; ++j) {
                    if (strcmp(mof_file_map_.left.at(static_cast<SpecialActionType>(j)).c_str(), motion_) == 0) {
                      act_motion_id_ = j;
                      break;
                    }
                  }
                } else {
                  myprintf("%s(%i) : error: motion_id format\n", name, line);
                  return false;
                }
              } else if (strcmp(sval[0], "transition") == 0) {
                bool found = false;
                if (!this_mof_has_labels) {
                  myprintf("%s(%i) : error: this line is unreachable, because there was no label before\n", name, line);
                  return false;
                }
                if (strcmp(sval[1], "allMotions") == 0) {
                  found = true;
                } else {
                  for (int j = 0; j < NUM_SPECIAL_ACTIONS; ++j) {
                    if (strcmp(mof_file_map_.left.at(static_cast<SpecialActionType>(j)).c_str(), sval[1]) == 0) {
                      found = true;
                      break;
                    }
                  }
                }

                if (!found) {
                  myprintf("%s(%i) : error: request for transition unknown\n", name, line);
                  return false;
                }

                if (c == 4) {
                  line_motion_id_[num_of_lines_] = static_cast<short>(act_motion_id_);
                  line_data_[num_of_lines_] = strdup(t);
                  line_number_[num_of_lines_++] = static_cast<short>(line);
                } else {
                  myprintf("%s(%i) : error: transition format\n", name, line);
                  return false;
                }
              } else if (strcmp(sval[0], "label") == 0) {
                if (c == 2) {
                  label_motion_[num_of_labels_] = strdup(motion_);
                  label_name_[num_of_labels_] = strdup(sval[1]);
                  label_number_[num_of_labels_++] = static_cast<short>(num_of_lines_);
                  this_mof_has_labels = true;
                } else {
                  myprintf("%s(%i) : error: label format\n", name, line);
                  return false;
                }
              } else if (strcmp(sval[0], "hardness") == 0) {
                if (!this_mof_has_labels) {
                  myprintf("%s(%i) : error: this line is unreachable, because there was no label before\n", name, line);
                  return false;
                }
                if (c == NUM_JOINTS + 2) {
                  char temp[1024];
                  temp[0] = 0;
                  strcat(temp, "hardness");
                  int val = 0;

                  for (int j = 1; j < NUM_JOINTS + 1; j++) {
                    if (strcmp(sval[j], "*") == 0) {
                      sprintf(sval[j], "%i", LEGACY_HARDNESS_DEFAULT);
                    }

                    if ((strcmp(sval[j], "-1") == 0 || sscanf(sval[j], "%i", &val) == 1) && val >= 0 && val <= 100) {
                      strcat(temp, " ");
                      strcat(temp, sval[j]);
                    } else {
                      myprintf("%s(%i) : error: hardness data format\n", name, line);
                      return false;
                    }
                  }
                  strcat(temp, " ");
                  strcat(temp, sval[NUM_JOINTS + 1]);

                  line_motion_id_[num_of_lines_] = static_cast<short>(act_motion_id_);
                  line_data_[num_of_lines_] = strdup(temp);
                  line_number_[num_of_lines_++] = static_cast<short>(line);
                } else {
                  myprintf("%s(%i) : error: hardness format\n", name, line);
                  return false;
                }
              } else if (c == NUM_JOINTS + 2) {
                char temp[1024];
                temp[0] = 0;
                int val = 0;
                if (!this_mof_has_labels) {
                  myprintf("%s(%i) : error: this line is unreachable, because there was no label before\n", name, line);
                  return false;
                }

                for (int j = 0; j < NUM_JOINTS; ++j) {
                  if (strcmp(sval[j], "*") == 0) {
                    sprintf(sval[j], "%i", static_cast<int>(JOINT_IGNORE));
                  }
                  if (strcmp(sval[j], "-") == 0) {
                    sprintf(sval[j], "%i", static_cast<int>(JOINT_OFF));
                  }

                  if ((strcmp(sval[j], "1000") == 0 || strcmp(sval[j], "2000") == 0 || sscanf(sval[j], "%i", &val) == 1) &&
                      val >= -210 && val <= 210) {
                    if (j != 0) {
                      strcat(temp, " ");
                    }
                    strcat(temp, sval[j]);
                  } else {
                    myprintf("%s(%i) : error: joint data format\n", name, line);
                    return false;
                  }
                }
                if (sscanf(sval[NUM_JOINTS], "%i", &val) == 1 && (val >= 0 && val <= 3)) {
                  strcat(temp, " ");
                  strcat(temp, sval[NUM_JOINTS]);
                } else {
                  myprintf("%s(%i) : error: interpolation data format\n", name, line);
                  return false;
                }
                if (sscanf(sval[NUM_JOINTS + 1], "%i", &val) == 1 && val > 0) {
                  strcat(temp, " ");
                  strcat(temp, sval[NUM_JOINTS + 1]);
                } else {
                  myprintf("%s(%i) : error: time data format\n", name, line);
                  return false;
                }
                line_motion_id_[num_of_lines_] = static_cast<short>(act_motion_id_);
                line_data_[num_of_lines_] = strdup(temp);
                line_number_[num_of_lines_++] = static_cast<short>(line);
              } else {
                myprintf("%s(%i) : error: illegal number of arguments\n", name, line);
                return false;
              }
              ++line;
              t = u + 1;
            } else {
              t += strlen(t);
            }
          }
        } else {
          myprintf("error reading from %s. Aborting.\n", name);
          return false;
        }
      }
      if (fd != nullptr) {
        do {
          ff = readdir(fd);
          there_are_more = ff != nullptr;
        } while (there_are_more && (strlen(ff->d_name) <= 4 || strcmp(ff->d_name + strlen(ff->d_name) - 4, ".mof") != 0));
      } else {
        there_are_more = false;
      }
    }
    if (fd != nullptr) {
      closedir(fd);
    }
    return true;
  }

  bool MofCompiler::parseExternMotionFile() {
    for (int& i : jump_table_) {
      i = -1;
    }

    char name[512];
    sprintf(name, "%s/config/mofs/extern.mof", installation_root_directory_.c_str());
    FILE* f = fopen(name, "r");
    if (f == nullptr) {
      myprintf("error opening %s. Aborting.\n", name);
      return false;
    }
    char s[128000] = {0};
    size_t siz = fread(s, 1, 128000, f);
    fclose(f);
    if (siz > 0) {
      s[siz] = 0;
      char* t = &s[0];
      int line = 1;
      while (*t != 0) {
        char* u = strchr(t, '\n');
        if (u >= t) {
          *u = 0;

          char sval[5][256];
          int c = sscanf(t, "%s %s %s %s %s", sval[0], sval[1], sval[2], sval[3], sval[4]);

          if (c == -1 || sval[0][0] == '"' || strncmp(sval[0], "//", 2) == 0 || strcmp(sval[0], "motion_id") == 0 ||
              strcmp(sval[0], "label") == 0) {
            // skip comments and empty lines by doing nothing
            // skip labels and id
          } else if (strcmp(sval[0], "transition") == 0 && c == 4) {
            bool found = false;
            if (strcmp(sval[1], "extern") == 0) {
              continue;
            }
            int i;
            for (i = 0; i < NUM_SPECIAL_ACTIONS; ++i) {
              if (strcmp(mof_file_map_.left.at(static_cast<SpecialActionType>(i)).c_str(), sval[1]) == 0) {
                found = true;
                break;
              }
            }
            if (!found) {
              myprintf("%s(%i) : error: special action '%s' unknown (not in SpecialActionRequest.h)\n", name, line, sval[1]);
              return false;
            }

            for (int j = 0; j < num_of_labels_; ++j) {
              if (strcmp(label_motion_[j], sval[2]) == 0 && strcmp(label_name_[j], sval[3]) == 0) {
                jump_table_[i] = label_number_[j];
                found = true;
                break;
              }
            }

            if (!found) {
              myprintf("%s(%i) : error: jump label '%s:%s' unknown (not in *.mof)\n", name, line, sval[2], sval[3]);
              return false;
            }

          } else {
            myprintf("%s(%i) : error: unexpected data\n", name, line);
            return false;
          }
          ++line;
          t = u + 1;
        } else {
          t += strlen(t);
        }
      }
    } else {
      myprintf("error reading from %s. Aborting.\n", name);
      return false;
    }

    for (int i = 0; i < NUM_SPECIAL_ACTIONS; ++i) {
      if (jump_table_[i] == -1) {
        myprintf("extern.mof(1): error: no motion net entry defined for special action %s\n ",
                 mof_file_map_.left.at(static_cast<SpecialActionType>(i)).c_str());
        return false;
      }
    }
    return true;
  }
  // NOLINTEND(readability-function-cognitive-complexity)

  bool MofCompiler::compileMotionFiles(char* buffer, size_t size) {
    print_buffer_ = buffer;
    print_buffer_size_ = size;
    print_buffer_[0] = 0;

    num_of_labels_ = 0;
    num_of_lines_ = 0;
    num_of_files_ = 0;

    std::memset(label_number_, 0, sizeof(label_number_));
    std::memset(motion_, 0, sizeof(motion_));
    std::memset(line_number_, 0, sizeof(line_number_));
    std::memset(line_motion_id_, 0, sizeof(line_motion_id_));
    std::memset(file_start_index_, 0, sizeof(file_start_index_));

    label_motion_[num_of_labels_] = strdup("extern");
    label_name_[num_of_labels_] = strdup("start");
    label_number_[num_of_labels_++] = static_cast<short>(num_of_lines_);

    line_data_[num_of_lines_] = strdup("transition allMotions extern start");
    line_number_[num_of_lines_++] = 1;

    if (!parseMotionFiles() || !parseExternMotionFile()) {
      return false;
    }

    // check whether the last line of every mof is an unconditional jump
    for (int i = 1; i <= num_of_files_; ++i) {
      int ind = i < num_of_files_ ? file_start_index_[i] - 1 : num_of_lines_ - 1;
      if (strncmp(line_data_[ind], "transition allMotions", 21) != 0) {
        myprintf(
          "%s(%i) : error: this mof does not end with a transition for allMotions\n", file_name_[i - 1], line_number_[ind]);
        return false;
      }
    }

    // check whether there are mofs without SpecialActionRequest::SpecialAction
    for (int i = 1; i < num_of_labels_; ++i) {
      if (strcmp(label_motion_[i], label_motion_[i - 1]) == 0) {
        continue;
      }
      bool found = false;
      for (int j = 0; j < NUM_SPECIAL_ACTIONS; ++j) {
        if (strcmp(label_motion_[i], mof_file_map_.left.at(static_cast<SpecialActionType>(j)).c_str()) == 0) {
          found = true;
          break;
        }
      }
      if (!found) {
        for (int j = num_of_files_ - 1; j >= 0; --j) {
          if (file_start_index_[j] <= label_number_[i]) {
            myprintf("%s(%i) : warning: there is no special action id for this mof\n", file_name_[j], 1);
            break;
          }
        }
      }
    }
    return generateMotionNet();
  }
} // namespace nomadz_motion_control
