#pragma once

#include <vector>

#include "nomadz_motion_control/walk_engine/planned_steps.hpp"
#include "nomadz_motion_control/walk_engine/walk_core_state.hpp"
#include "walk_engine_parameters.hpp"

namespace nomadz_motion_control {

  class StepPlanner {
    using Twist2D = nomadz_core::Twist2D;
    using Pose2D = nomadz_core::Pose2D;
    using Acc2D = Twist2D;
    using Side = nomadz_definitions::side::Side;

  public:
    StepPlanner(const std::shared_ptr<walk_engine_parameters::Params> dyn_params);

    void reset();

    /**
     * Calculates the step pattern based on the given walk core state.
     * This is also the main update function of the step planner.
     *
     * @param walk_core_state The walk core state provided by the WalkEngine.
     */
    void calcStepPattern(const WalkCoreState& walk_core_state);

    /**
     * Returns the planned steps generated by the step planner.
     *
     * @return The planned steps. Contain all information required by the WalkEngine to perform the remaining steps.
     */
    PlannedSteps getPlannedSteps() const { return planned_steps_; };

    void setBallPos(const Eigen::Vector2f& ball_pos);

    void setKickRequest(float kick_direction, float kick_power);

    bool getExecutingTargetPattern() const { return !executing_target_pattern_; } // invert

  private:
    void updateFromCoreState(const WalkCoreState& walk_core_state);

    void estimateSpeed();

    Twist2D processSpeedRequest(const Twist2D& target_speed);

    // Pattern mode related functions
    void calcNextGaitPatterns(const WalkCoreState& walk_core_state);

    std::vector<Step> perStepGenerator(const Step& initial_target_step);

    void calcPreviewGaitsFromSpeed(const Twist2D& requested_speed, float step_duration);

    void calcTargetFootPoses();

    void updateHistory();

    /**
     * Calculates the effective origin pose difference based on the support foot offset and the requested origin pose
     * difference.
     *
     * @param support_foot_offset The offset of the support foot.
     * @param requested_origin_pose_diff The requested origin pose difference.
     * @return The calculated effective origin pose difference.
     */
    static Twist2D calcEffectiveOriginPoseDiff(const Twist2D& support_foot_offset,
                                               const Twist2D& requested_origin_pose_diff);

    /**
     * Calculates the phase duration based on the requested speed.
     *
     * @param requested_speed The final processed speed that should be executed.
     * @return The calculated phase duration for the next step.
     */
    float calcPhaseDuration(const Twist2D& requested_speed);

    /**
     * Helper function to computes the origin pose based on two steps.
     *
     * @param step1 The first step.
     * @param step2 The second step.
     * @return The computed origin pose.
     */
    static Pose2D computeOriginFromSteps(const Step& step1, const Step& step2);

    /**
     * Computes the next step based on the origin pose and the support step.
     * Note: this function contains heuristics to account for the return offset of the support foot.
     *
     * @param next_origin The next origin pose.
     * @param next_support_step The next support step.
     * @return The computed next step.
     */
    Step computeNextStepFromOrigin(const Pose2D& next_origin, const Step& next_support_step);

    /**
     * Updates the foot pose limits based on the origin pose difference.
     *
     * @param origin_pose_diff The origin pose difference.
     */
    void updateFootPoseLimits(const Twist2D& origin_pose_diff);

    static constexpr int MIN_UPCOMING_PATTERN = 5;
    static constexpr Twist2D MAX_SPEED{0.25F, 0.25F, 2.0F};
    static constexpr Acc2D MAX_ACCELERATION{0.05F, 0.1F, 0.5F};
    static constexpr float BASE_WALK_PERIOD = 0.25F;
    static constexpr Twist2D WALK_PERIOD_INCREASE_FACTOR{0.1F, 0.1F, 0.01F};
    static constexpr FootPoses FOOT_DEFAULT_POSE{Pose2D{0.F, 0.05F, 0.0F}, Pose2D{0.F, -0.05F, 0.0F}};

    // the left foot is used here as reference
    static constexpr float FOOT_SELF_COLLISION_LIMIT_Y = 0.045F;
    static constexpr float FOOT_OUTWARDS_ROTATION_LIMIT_FACTOR = 2.F / 3.F;
    static constexpr float FOOT_INWARDS_ROTATION_LIMIT_FACTOR = 1.F / 3.F;
    const std::shared_ptr<walk_engine_parameters::Params> dyn_params_;

    FootPoses measured_foot_poses_;
    FootPoses last_measured_foot_poses_;
    FootPoses last_foot_poses_;

    std::vector<Step> upcoming_steps_;
    std::vector<Pose2D> upcoming_way_points_;

    // preview step pattern generated from the request speed command (speed mode), current speed (pattern mode)
    std::vector<Step> preview_steps_;
    std::vector<Pose2D> preview_way_points_;

    Side swing_side_{Side::RIGHT};
    Side support_side_{Side::LEFT};
    Side last_support_side_{Side::LEFT};

    float step_duration_{0.25F};

    bool initialized_{false};
    Twist2D request_speed_{};
    Twist2D last_executed_speed_{};
    Twist2D measured_speed_{};
    Twist2D current_executed_speed_{};
    Pose2D last_odometry_{};

    PlannedSteps planned_steps_;
    FootPoses foot_pose_lower_limits_{};
    FootPoses foot_pose_upper_limits_{};
    Eigen::Vector2f ball_position_;
    bool executing_target_pattern_{false};

    std::vector<Step> target_steps_;
    std::vector<Pose2D> target_way_points_;
    float kick_direction_{0.F};
    float kick_power_{0.F};
    int cool_down_counter_{0};
  };

} // namespace nomadz_motion_control
