<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>nomadz_led_control</name>
  <version>0.0.1</version>
  <description>LED Debugging on Robot</description>
  <maintainer email="nomadz@list.ee.ethz.ch">Team NomadZ</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>nao_lola_command_msgs </depend>
  <depend>nomadz_communication_msgs </depend>
  <depend>nomadz_motion_control_msgs</depend>
  <depend>nomadz_modeling_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
