<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>nomadz_modeling</name>
  <version>0.0.1</version>
  <description>self localization package</description>
  <maintainer email="nomadz@list.ee.ethz.ch">Team NomadZ</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>spdlog</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>rclcpp_components</depend>
  <depend>generate_parameter_library</depend>
  <depend>nomadz_core</depend>
  <depend>nomadz_configuration</depend>
  <depend>nomadz_behavior_msgs</depend>
  <depend>nomadz_image_processing</depend>

  <depend>nomadz_modeling_msgs</depend>
  <depend>nomadz_motion_control_msgs</depend>
  <depend>nomadz_vision_msgs</depend>
  <depend>nomadz_communication_msgs</depend>
  <depend>boost</depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
