motion_id = fallprotectionside
"test

label start

hardness       15     15           15     15     15     15     15     15           15     15     15     15     20     20           20     20     20     20     20     20           20     20     20     20     20     20            0

"              HY     HP          LSP    LSR    LEY    LER    LWY     LH          RSP    RSR    REY    RER    RWY     RH         LHYP    LHR    LHP    LKP    LAP    LAR         RHYP    RHR    RHP    RKP    RAP    RAR          Int    Dur
             -0.5     20           90      0      0      0     -0      0           90     -0     -0     -0      0      0            0     -0    -53    120    -67    0.1            0      0    -53    120    -67      0            1    100

hardness       15     15           15     15     15     15     15     15           15     15     15     15     20     20           20     20     20     20     20     20           20     20     20     20     20     20            0
             -0.5     20           90     -0      0      0     -0      0           90      0     -0     -0      0      0            0     -0    -53    120    -67    0.1            0      0    -53    120    -67      0            1    800

label repeat

hardness       80     80           40     40     40     40     40     40           40     40     40     40     40     40           60     60     60     60     60     60           60     60     60     60     60     60            0
                *      *           90   10.1      0      0    -90      0         90.5   -9.8     -0     -0     90      0            0     -0  -21.3   48.9  -27.6   -0.1           -0      0  -21.2     49  -27.6      0            1    500

transition fallprotectionside fallprotectionside repeat

transition allMotions extern start
