motion_id = genuflect2Up

label start
" genuflect end pos
hardness       80     80            5     20     40     40     40     40            5     20     40     40     40     40           60     60     60     60     60     60           60     60     60     60     60     60            0
"              HY     HP          LSP    LSR    LEY    LER    LWY     LH          RSP    RSR    REY    RER    RWY     RH         LHYP    LHR    LHP    LKP    LAP    LAR         RHYP    RHR    RHP    RKP    RAP    RAR          Int    Dur
                0   -0.7         60.4   20.1   20.8   -0.3    -90      0         91.4  -33.2  -20.5    1.1     90      0          -58   37.1    -80  109.2     10    -21          -58  -37.1    -80  109.2     10     21            1    200

                *      *         60.4   20.1   20.8   -0.3    -90      0         91.4  -33.2  -20.5    1.1     90      0        -45.2   26.4  -59.8  108.1  -23.5  -20.8        -45.2  -37.1  -67.8   99.7   -6.8   24.7            1    200

                *      *         60.4   20.1   20.8   -0.3    -90      0         91.4  -33.2  -20.5    1.1     90      0        -36.2   14.4  -59.8  108.1  -32.5   -5.8        -36.2   -5.4  -70.8   99.7  -10.5    5.7            1    200

hardness       80     80            5     20     40     40     40     40            5     20     40     40     40     40           80     80     80     80     80     80           80     80     80     80     80     80            0
                *      *         60.4   20.1   20.8   -0.3    -90      0         91.4  -33.2  -20.5    1.1     90      0        -30.2    5.4  -59.8  108.1  -32.5  -15.8        -30.2   -5.4  -63.8   99.7  -22.5    5.7            1    500

" sitDownKeeper

hardness       20     20            5     20     40     40     40     40            5     20     40     40     40     40           60     60     60     80     80     60           60     60     60     80     80     60            0
                *      *           94     17      0     -1    -90      0           94    -17     -0      1     90      0         -0.4   -1.9  -51.9  122.6    -70    1.7         -0.4   -0.6  -52.2  121.9  -70.7    0.6            1    500

" goUp
                *      *           90   11.5      0      0    -90      0           90  -11.5     -0     -0     90      0            0     -0  -21.3   48.9  -27.6    0.1            0      0  -21.2     49  -27.6      0            1    500

" stand
label repeat
                *      *           90   10.1      0      0    -90      0         90.5   -9.8     -0     -0     90      0            0     -0  -21.3   48.9  -27.6   -0.1           -0      0  -21.2     49  -27.6      0            1     50

transition genuflect2Up genuflect2Up repeat

transition allMotions extern start
