motion_id = getUpBackNao22
"Simple stand up when Nao is lying on back
label start


hardness       70     70           70     70     70     70     70     70           70     70     70     70     70     70           90     90     90     90     90     90           90     90     90     90     90     90          500
"              HY     HP          LSP    LSR    LEY    LER    LWY     LH          RSP    RSR    REY    RER    RWY     RH         LHYP    LHR    LHP    LKP    LAP    LAR         RHYP    RHR    RHP    RKP    RAP    RAR          Int    Dur
                0     30          119   38.4    2.1  -78.4    -90      0        119.5  -50.2   -7.3   88.5     90      0          0.7    3.5   20.6   88.5    7.2    4.5          0.7   -0.3   23.1   86.8      5   -0.2            1    400
                0     30        119.5     12      5    -85    -30      0        119.5    -12     -5     85     30      0            0     -0     25     35     50     -0            0      0     25     35     50      0            1    300

    "ArmPushing
                0     30          120     12      5    -85    -30      0          120    -12     -5     85     30      0            0     -0    -55     57     57     -0            0      0    -55     57     57      0            1    400
                0     30          115      0     20    -20    -30      0          115     -0    -20     20     30      0          -60     30    -90     87     44      4          -60    -24    -89    104     33      1            1    300
    "Split
              7.5     30        100.8     -5     15    -20    -90      0        101.6      5   87.5  -12.2     90      0        -56.3   18.6    -91   75.5   51.6   -4.8        -56.3  -10.7    -91     73   52.2    7.6            1    250

    "old stand up
              6.9     30          110   -4.8     10  -18.6    -90      0        111.6    2.9   87.4  -12.4     90      0          -63   41.7  -80.2   76.5   49.3   -7.2          -63  -32.5    -84   81.8   47.1    1.1            1    150
              5.5   29.4          105     10    -10   -5.9    -90      0        110.7  -39.7   99.4   -8.2     90      0          -63   11.7  -28.7  121.6    -36    -15          -63  -20.3  -88.4   48.2   52.6     -1            1    500
              5.5     10          100     15    -15      0    -90      0        110.7    -35   99.4   -8.2     90      0          -63   11.7  -28.7  121.6    -36    -15          -63  -20.3  -88.4   48.2   52.6      8            1    100

                0      5           90     23    -30      0    -90      0           90    -25     88   -8.2     90      0          -53     10    -54    120    -37     -5          -53    -15    -70    100     -5     20            1    250
                0     -0           85     25    -65      0    -90      0           85    -25     85     -0     90      0          -45     10    -54    120    -37     -5          -45    -10    -58    120    -37      7            1    300
                0     -5           81     25    -85  -14.4    -90      0           81    -25     85   -7.8     90      0          -33     -2    -54    120    -49      3          -33      2    -54    120    -49     -3            1    250

              4.9     15           72   12.8  -84.1  -12.1    -90      0         75.4  -12.8   99.2   -6.8     90      0          0.2     -1    -53    120    -67     -1          0.2      1    -53    120    -67      1            1    500
                0     15           90     10      0      0    -90      0           90    -10     -0     -0     90      0            0     -0    -36     71    -35     -0            0      0    -36     71    -35      0            1    600

label repeat
hardness       80     80           40     40     40     40     40     40           40     40     40     40     40     40           90     90     90     90     90     90           90     90     90     90     90     90            0
                *      *           90     10      0      0    -90      0           90    -10     -0     -0     90      0            0     -0  -21.3   48.9  -27.6   -0.1           -0      0  -21.2     49  -27.6      0            1    200
transition getUpBackNao22 getUpBackNao22 repeat
transition allMotions extern start
