motion_id = jointCalibrationStandStiff
"test

label start

hardness      100    100          100    100    100    100      0      0          100    100    100    100      0      0          100    100    100    100    100    100          100    100    100    100    100    100            0

"              HY     HP          LSP    LSR    LEY    LER    LWY     LH          RSP    RSR    REY    RER    RWY     RH         LHYP    LHR    LHP    LKP    LAP    LAR         RHYP    RHR    RHP    RKP    RAP    RAR          Int    Dur
                0     -0           90     10      0      0    -90      0           90    -10     -0     -0     90      0            0     -0      0      0      0     -0            0      0      0      0      0      0            1    500
label repeat
                0     -0           90     10      0      0    -90      0           90    -10     -0     -0     90      0            0     -0      0      0      0     -0            0      0      0      0      0      0            1    100

transition jointCalibrationStandStiff jointCalibrationStandStiff repeat

transition allMotions extern start
