motion_id = standWide
"test

label start

hardness       40     40           40     40     40     40     40     40           40     40     40     40    100    100          100    100    100    100    100    100          100    100    100    100    100    100            0

"              HY     HP          LSP    LSR    LEY    LER    LWY     LH          RSP    RSR    REY    RER    RWY     RH         LHYP    LHR    LHP    LKP    LAP    LAR         RHYP    RHR    RHP    RKP    RAP    RAR          Int    Dur
             -0.5   20.3           90   11.5      0      0    -90      0           90  -11.5     -0     -0     90      0            0      5  -21.3   48.9  -27.6     -5            0     -5  -21.2     49  -27.6      5            1    500
label repeat
hardness       80     80           40     40     40     40     40     40           40     40     40     40     40     40           60     60     60     60     60     60           60     60     60     60     60     60            0
                *      *           90   10.1      0      0    -90      0         90.5   -9.8     -0     -0     90      0            0      5  -21.3   48.9  -27.6     -5           -0     -5  -21.2     49  -27.6      5            1     50
transition standWide standWide repeat

transition allMotions extern start
