<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>nomadz_webots_controller</name>
  <version>0.0.1</version>
  <description>This package allows the user to use both webots nao lola controller as well as the webots_ros2 APIs to interactive with the webots simulation environment</description>
  <maintainer email="nomadz@list.ee.ethz.ch">Team NomadZ</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>nao_lola_command_msgs</depend>
  <depend>nao_lola_sensor_msgs</depend>
  <depend>nomadz_modeling_msgs</depend>
  <depend>webots_ros2_driver</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
